### ISSUE TITLE
Docker exits - unhealthy container 

### ISSUE THREAD

**Issue by mikkel1156** [ferdium/ferdium-server#43]
Trying to deploy the container over swarm (however it's only able to schedule on one node, so basically like docker-compose) usising bind mounts. However after some time it will exit with `task: non-zero exit (137): dockerexec: unhealthy container`

Which I'm assuming is coming from the healthcheck.

Docker stack/compose file
```
version: '3'
services:
  srv:
    image: ghcr.io/ferdium/ferdium-server:latest
    restart: unless-stopped
    networks:
      - traefik-net
    environment:
      TZ: Europe/Copenhagen
      GENERIC_TIMEZONE: Europe/Copenhagen
      DATA_DIR: /data
      DB_CONNECTION: sqlite
      MAIL_CONNECTION: smtp
      SMTP_HOST: xxxxxxxxxxxxx
      SMTP_PORT: 465
      MAIL_SSL: "true"
      MAIL_USERNAME: xxxx@xxxx.xxx
      MAIL_PASSWORD: "xxxxxxxxxxxxxxxxxxxx"
      MAIL_SENDER: xxxx@xxxx.xxx
      IS_CREATION_ENABLED: "true"
      IS_DASHBOARD_ENABLED: "true"
      IS_REGISTRATION_ENABLED: "true"
      CONNECT_WITH_FRANZ: "false"
    volumes:
      - /srv/docker/ferdium/data:/data
      - /srv/docker/ferdium/recipes:/app/recipes
    deploy:
      placement:
        constraints:
          - "node.hostname == docker1"
      labels:
        traefik.enable: 'true'
        traefik.http.services.ferdium.loadbalancer.server.port: 3333
        traefik.http.routers.ferdium.rule: Host(`ferdium.zerosrealm.xyz`)
        traefik.http.routers.ferdium.tls: "true"
        traefik.docker.network: traefik-net

networks:
  traefik-net:
    external: true

```

This is the container logs (note this is subsequent runs, the first container that setup everything had same issue)
```
-------------------------------------
       ______              ___
      / ____/__  _________/ (_)_  ______ ___
     / /_  / _ \/ ___/ __  / / / / / __ `__ \
    / __/ /  __/ /  / /_/ / / /_/ / / / / / /
   /_/    \___/_/   \__,_/_/\__,_/_/ /_/ /_/
      _____
     / ___/___  ______   _____  _____
     \__ \/ _ \/ ___/ | / / _ \/ ___/
    ___/ /  __/ /   | |/ /  __/ /
   /____/\___/_/    |___/\___/_/
Brought to you by ferdium.org
**** Updating recipes ****
Saved working directory and index state WIP on main: 6cbc1977 Upgrade 'node' to '16.15.1' and 'pnpm' to '7.3.0'
Already up to date.
Already up to date.
On branch main
Your branch is up to date with 'origin/main'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.pnpm-store/
nothing added to commit but untracked files present (use "git add" to track)
Dropped refs/stash@{0} (642a56ed72969ef5c58e6b868ba10e2274f1a8d5)
npm WARN using --force Recommended protections disabled.
added 1 package, and audited 2 packages in 2s
1 package is looking for funding
  run `npm fund` for details
found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.12.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.12.2>
npm notice Run `npm install -g npm@8.12.2` to update!
npm notice 
Scope: all 238 workspace projects
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
. prepare$ pnpm dlx husky install
. prepare: .pnpm-store/v3/tmp/dlx-81                | Progress: resolved 1, reused 0, downloaded 0, added 0
. prepare: .pnpm-store/v3/tmp/dlx-81                |   +1 +
. prepare: Packages are hard linked from the content-addressable store to the virtual store.
. prepare:   Content-addressable store is at: /app/recipes/.pnpm-store/v3
. prepare:   Virtual store is at:             .pnpm-store/v3/tmp/dlx-81/node_modules/.pnpm
. prepare: husky - Git hooks installed
. prepare: .pnpm-store/v3/tmp/dlx-81                | Progress: resolved 1, reused 1, downloaded 0, added 1, done
. prepare: Done
> ferdium-recipes@1.0.1 package /app/recipes
> node scripts/package.js
✅ Successfully packaged and added 236 recipes (0 unsuccessful recipes)
**** App key is XXXXXXXXXXXXXXX. You can modify `/data/FERDIUM_APP_KEY.txt` to update the app key ****
Nothing to migrate
```
After some time it will stop and start a new container, with the earlier reason from Docker.

Going inside the container while it's "waiting" PSexec and ps shows that all it's running is the entrypoint and the chown command. I find this strange since the chown command should be running before the migration (from looking at the entrypoint.sh file in repo) - but the migration seems to run fine (note the `Nothing to migrate`).

Wanted to try removing the chown command from the entrypoint.sh file, but I wasn't able to successfully build the image (due to some node/npm build issues, which isn't related).
