### ISSUE TITLE
Custom service icons don't work when using ferdium-server

### ISSUE THREAD

**Issue by typoworx-de** [ferdium/ferdium-server#64]
I've setup my own ferdium server and migrated from ferdi (with local data) using export/import to my new ferdium-server. At first it looked like working, but all custom-logos I had on Ferdi (local account only) were missing.

I've tried to re-apply them all manually to the services like multiple teams-accounts (different customers/projects), but they won't appear! Even in service it shows up like "missing image" in HTML website.

So my generic question is - should this work? Are the custom service-icons stored on the ferdium-server profile?!
And what at all is stored at ferdium-server is my login data stored there, too or only the defined services without anything else?!

**Comment by typoworx-de** [comment]
I'm not shure if this is a ferdium-server or ferdium-app (client) issue.

After opening I've done some tests today to check:

1. Installed Ferdium on Linux (additionally to Macbook). Same behaviour here! :x: 
2. Exited Ferdium Session and used Ferdium without Ferdium-Server. Custom Icons for Services are working! :heavy_check_mark: 

So it looks like there is some issue on client and/or server side to store the custom service images correctly. To confirm right after trying to customize a logo:

Before saving after choosing custom Icon:
![image](https://user-images.githubusercontent.com/1282298/216571250-280467b7-c3d9-4e88-85e4-a99f748c92c5.png)

After saving, the menu-place where this service is/should be is gray (same like background) with no logo or outline where the custom icon should appear!

Trying to edit the service looks like this. Notice the custom-icon looks "lost".
![image](https://user-images.githubusercontent.com/1282298/216571627-fb5fa889-776f-40a5-9611-4517fb461004.png)

I still can delete the non-existing custom-icon image. But repeating to chose one doesn't work either.

Same service custom-icons work on my old Ferdi with local use (no ferdi server). Same with Ferdium used locally only.

**Comment by typoworx-de** [comment]
As I've setup a private ferdium-server instance for my company I also tested now with official ferdium-server. Surprisingly there the custom service-icons work!

So I'm shure there must be something wrong with ferdium-server instance I've setup.

**Comment by Zaczero** [comment]
I face the same issue, here's my docker-compose.yml:

```yml
version: '3.9'

services:
  ferdium-server:
    image: ferdium/ferdium-server
    restart: unless-stopped

    environment:
      NODE_ENV: development
      APP_URL: localhost
      DB_CONNECTION: sqlite
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: ferdium
      DB_SSL: "false"
      MAIL_CONNECTION: smtp
      SMTP_HOST: 127.0.0.1
      SMTP_PORT: 2525
      MAIL_SSL: "false"
      MAIL_USERNAME: username
      MAIL_PASSWORD: password
      MAIL_SENDER: noreply@ferdium.org
      IS_CREATION_ENABLED: "true"
      IS_DASHBOARD_ENABLED: "true"
      IS_REGISTRATION_ENABLED: "true"
      CONNECT_WITH_FRANZ: "false"
      DATA_DIR: /data
      PUID: 1000
      PGID: 1000

    ports:
      - 127.0.0.1:3333:3333

    volumes:
      - ./data/data:/data
      - ./data/recipes:/app/recipes
```

**Comment by Ryonez** [comment]
It seems that the server stores the images in the `/app/tmp` directory. the logs for me indicate there's read/write issues there.

Following the suggestion here https://github.com/ferdium/ferdium-app/issues/621#issuecomment-1320866104, I set up a directory link with read/write perms and it seems to be functioning now.

**Comment by typoworx-de** [comment]
Thanks for the hint @Ryonez. I've checked out the git-project and tried to apply some fixes to the Dockerfile and entrypoint:
mkdir -p /app/tmp

and I also had some strange issues regarding missing node-modules, which resulted in patching the second Dockerfile stage like this (in short):
```
RUN \
  PNPM_VERSION=$(node -p 'require("./package.json").engines.pnpm'); npm i -g pnpm@$PNPM_VERSION; \
  pnpm i image-size; \
  pnpm i simple-git; \
  pnpm i sqlite3@^5.0.0; \
  npm i -g @adonisjs/cli
```

I though image-size module would have been the culprit. The ferdium-server starts now, but still I cannot save custom icons! The file is uploaded to /app/tmp but still doesn't work when using ferdium-client.

And I still don't understand why is ferdium-server only building and working correctly running it with NODE_ENV=development?!

I've been trying to set NODE_ENV=development only for build-stage and use production for the final stage. But this results in many other problems.

Any suggestions?!

**Comment by Ryonez** [comment]
I'm not sure about the node stuff, but with the tmp dir, don't just create it in the container (I didn't at all), mount it, like this:
```
-v <path to data>:/data \
-v <path to recipes>:/app/recipes \
-v <path to tmp>:/app/tmp \
```
It's data you want to be persistent, and while a weird place, `/app/tmp/uploads` seems to be the permanent home for the icons, not just as a temporary storage.

**Comment by SpecialAro** [comment]
Closing as per https://github.com/ferdium/ferdium-app/issues/928#issuecomment-1755124221

**Comment by SpecialAro** [comment]
NOTICE:
If you update to the latest ferdium-server version you should change the paths of the recipes and tmp folders as follows:
- ./data/recipes:/app **/build** /recipes
- ./data/tmp:/app **/build** /tmp

**Comment by Ryonez** [comment]
@SpecialAro The documentation should be updated to reflect this, it's currently out of date.

**Comment by Ryonez** [comment]
Rolling back to [1.3.16](https://hub.docker.com/layers/ferdium/ferdium-server/1.3.16/images/sha256-da1423e02cfc52a4c5cb8a8c157dd13ca3f135269ba08f8d96a2b64b3cfd3979?context=explore), there are breaking changes even making the changes mentioned above. Wasn't able to login to the user account dashboard to check on things.

**Comment by SpecialAro** [comment]
@Ryonez, would you be able to provide your docker compose (coment out any sensitive info) so I can see the issue you are facing?

Also, the logs inside the container are very much appreciated.

**Comment by BhasherBEL** [comment]
Using latest docker image, I have this issue if I don't specify `https://` in `APP_URL`. Trough I can *understand* it, when using the app, it's a bit strange to get a "success" when uploading, and also that this is, afaik, the only issue with not specify the `https://` in front of the `APP_URL`. Is there a specific reason for that ?

**Comment by ClassickTech** [comment]
I am still having this bug. None of the suggested fixes worked for me. Here is my docker-compose
```
version: "2"
services:
  ferdium-server:
    image: ferdium/ferdium-server:latest
    container_name: ferdium-server
    environment:
      - NODE_ENV=production
      - APP_URL=https://api.ferdium.org
      - DB_CONNECTION=sqlite
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=sjdhfsdheywiqind
      - DB_DATABASE=ferdium
      - DB_SSL=false
      - MAIL_CONNECTION=smtp
      - SMTP_HOST=127.0.0.1
      - SMTP_PORT=2525
      - MAIL_SSL=false
      - MAIL_USERNAME=username
      - MAIL_PASSWORD=password
      - MAIL_SENDER=noreply@something.com
      - IS_CREATION_ENABLED=true
      - IS_DASHBOARD_ENABLED=true
      - IS_REGISTRATION_ENABLED=true
      - CONNECT_WITH_FRANZ=false
      - DATA_DIR=/data
      - JWT_USE_PEM=true
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - AUTO_UPDATE=true #optional 
    volumes:
      - /home/ctech/Documents/docker/ferdium/data:/data
      - /home/ctech/Documents/docker/ferdium/data/tmp:/app/build/tmp
      - /home/ctech/Documents/docker/ferdium/data/recipes:/app/build/recipes
    ports:
      - 3333:3333
    restart: unless-stopped
volumes:
  ferdium-recipes-vol:
```
Any help?
